### ISSUE TITLE
Allowing comments in target_file

### ISSUE THREAD

**Issue by mcbazza** [Tib3rius/AutoRecon#101] opened 2021-08-23 20:06 UTC
Just tried using a target file that I'm currently using against nmap (that has comments after the IP on a line) and it failed in AutoRecon.

However, I'm not one to be help back by things like that.
So, I've poked around, done some google and come up with:

Was (from autorecon.py, line 810):
```                for line in lines.splitlines():
                    line = line.strip()
                    if line.startswith('#') or len(line) == 0: continue
                    if line not in raw_targets:
                        raw_targets.append(line)
```

To:
```                for line in lines.splitlines():
                    if line.startswith('#') or len(line) == 0: continue
                    m = re.match(r'^([^#]*)#(.*)$', line)
                    if m: # Does the target line contain a # comment marker
                        line = m.group(1)
                    line = line.strip()
                    if line not in raw_targets:
                        raw_targets.append(line)
```

I'm no python dev and cannot tell a lie, I got the snippet from: https://www.rosettacode.org/wiki/Strip_comments_from_a_string#Python
Therefore, no warranty given, or implied!

Testing it here and is working a treat.

Apologies for lack of fork/push, I'm too new/shy to DevOps to chance it.

**Comment by Tib3rius** [comment] 2021-08-24 20:12
Could you give me an example of how the failing file looks? I'm not sure I understand, there were # after the IP? In that case AutoRecon is working as intended. The problem is with the input file.

**Comment by mcbazza** [comment] 2021-08-24 21:05
Hey there. Appreciate the rapid response. This is the non-beta version I'm using/referencing. I made the mod on my Kali VM. I'm testing this in a Kali WSL2 with un-modified latest code:

Target file looks like:
```bazza@DESKTOP-xxxxxxx:~$ cat autorecon-targets
# This is a comment line, no target
192.168.100.1   # this is a comment
192.168.100.2   # this is another comment
192.168.100.3
```
Output
```bazza@DESKTOP-xxxxxxx:~$ autorecon -t autorecon-targets
[!] 192.168.100.1       # this is a comment does not appear to be a valid IP address, IP range, or resolvable hostname.
[!] 192.168.100.2   # this is another comment does not appear to be a valid IP address, IP range, or resolvable hostname.
```
.1 has a tab, .2 has spaces, .3 has no comment.
No scan is performed. No idea why it doesn't attempt .3

If I modify the code as above, the output looks like:
```bazza@DESKTOP-xxxxxxx:~$ autorecon -t autorecon-targets
[*] Scanning target 192.168.100.1
[*] Scanning target 192.168.100.2
[*] Scanning target 192.168.100.3
[*] Running service detection nmap-top-20-udp on 192.168.100.1
```
And the scan works.

From what I understand, the code currently looks for empty lines, or lines where the first char is a #.
With this minor mod, it parses out the comment, keeping the text (that is hopefully an IP) prior to it.

This is how nmap target files work, which is how I stumbled upon this.
I have scheduled nmap scans on a work VM using target files that are commented like this.
I had tried moving over to AutoRecon as a test.
Then rather than maintain 2x target files, I set about trying to understand some minimal Python and making this minor tweak.

While I still have your attention. Kudos for this tool. Was such a great benefit whilst studying OSCP.

**Comment by Tib3rius** [comment] 2021-08-24 21:17
Hmm, ok. I'll check it out. I wasn't aware Nmap handled files with comments like that. It seems a little odd but let me do some tests and make sure it works with hostnames, etc. without screwing anything up.

**Comment by Tib3rius** [comment] 2021-08-29 04:11
@mcbazza can you check the latest beta? This should be fixed. Let me know if not. Thanks.

**Comment by Tib3rius** [comment] 2021-08-31 03:14
I'll close this as I'm pretty sure it works fine. Please comment if not, thanks!

**Closed by Tib3rius** 2021-08-31 03:14 UTC
Labels: enhancement
